wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.0
    cli_version: 0.16.1
    framework: huggingface
    huggingface_version: 4.35.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1704460553.707851
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 105
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 105
      3:
      - 23
      4: 3.11.0
      5: 0.16.1
      6: 4.35.2
      8:
      - 4
      - 5
      13: darwin-arm64
